version: '2.1'

orbs:
  browser-tools: circleci/browser-tools@1.2.3

jobs:
  test:
    docker:
      - image: 'cimg/node:16.11.1-browsers'
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Check chrome install
          command: |
            google-chrome --version
            chromedriver --version
      - run:
          name: Install dependencies
          command: |
            ls
            cd ..
            ls
            npm install
      - run:
          name: Run tests
          command: npm test

workflows:
  test:
    jobs:
      - test